### PR TITLE
Android SDK docs

### PR DESCRIPTION
**Pull request by Tonkonozhenko**

### CODE REVIEW

**Comment by bogdan** [comment]
I think we should recommend to overwrite talkable activity for all users. I think 90% of integrations will do that.

**Comment by Tonkonozhenko** [comment]
I think we should leave it in `Advanced` section because it's not required to do this.

**Comment by bogdan** [comment]
Yes, it is not required. But it is very likely to happen. I can't imagine an integration without some overwrite... especially in the display UI.

**Comment by Tonkonozhenko** [comment]
I'll add references from `Standalone` and `Post-Purchase` pages to that page and will rename it to `Overriding defaults`.

**Comment by bogdan** [comment]
LG

**Comment by Tonkonozhenko** [comment]
Merged and deployed via CLI

**Pull request closed without merging**
